services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
#    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules/
    networks:
      - database

  mongo:
    image: mongo
#    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - database

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
#    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_ROOT_URL}
      ME_CONFIG_BASICAUTH: false
    networks:
      - database

networks:
  database: